server.port=8081
server.servlet.session.cookie.name=PARAMEDIC_SESSIONID
spring.application.name=paramedic-ui
engine.api.url=http://localhost:8080/api/emergency

vaadin.launch-browser=false
vaadin.liveReload.enabled=false
vaadin.devmode.liveReload.enabled=false
