vaadin.launch-browser=false
vaadin.liveReload.enabled=false
vaadin.devmode.liveReload.enabled=false
spring.devtools.livereload.enabled=false
spring.devtools.restart.enabled=false

server.servlet.session.cookie.name=ENGINE_SESSIONID
spring.application.name=engine

# 1. H2 In-Memory Database Configuration
spring.datasource.url=jdbc:h2:mem:smartdispatchdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Hibernate/JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Enable the Web Console (So you can look at your data in a browser!)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console